### ISSUE TITLE
llama not start over start-webui.bat

### ISSUE THREAD

**Issue by alextomskras** [oobabooga/one-click-installers#1]
Hello.
if I try start llama decapoda-research/llama-7b-hf-int4 over start-webui.bat - all crashed
Please what need todo

Loading llama-7b-hf-int4...                                                                                             CUDA extension not installed.                                                                                           Traceback (most recent call last):                                                                                        File "H:\one-click-installers-oobabooga-windows\text-generation-webui\server.py", line 243, in <module>                   shared.model, shared.tokenizer = load_model(shared.model_name)                                                        File "H:\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model         model = load_quantized(model_name)                                                                                    File "H:\one-click-installers-oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 64, in load_quantized                                                                                                                         model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)                                         TypeError: load_quant() missing 1 required positional argument: 'groupsize'

**Comment by oobabooga** [comment]
```
mkdir repositories
cd repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
cd GPTQ-for-LLaMa
git reset --hard 468c47c01b4fe370616747b6d69a2d3f48bab5e4
python setup_cuda.py install
```

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-installation

**Comment by alextomskras** [comment]
Thanks for your answer but how i can make C++ build on windows10.
i'm create bat file for down into conda env.
after make conda activate created env and catch error about C++

`(base) H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install                                                                                                                 Traceback (most recent call last):                                                                                        File "H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 6, in <module>                                                                                                             ext_modules=[cpp_extension.CUDAExtension(                                                                             File "H:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1047, in CUDAExtension                                                                                                  library_dirs += library_paths(cuda=True)                                                                              File "H:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths                                                                                                  paths.append(_join_cuda_home(lib_dir))                                                                                File "H:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2230, in _join_cuda_home                                                                                                raise EnvironmentError('CUDA_HOME environment variable is not set. '                                                OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.                                                                                                                                                    (base) H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>conda activate textgen                                                                                                                                                                                                                                               EnvironmentNameNotFound: Could not find conda environment: textgen                                                      You can list all discoverable environments with `conda info --envs`.                                                                                                                                                                                                                                                                                                                                                                                                                            (base) H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>conda info --envs    # conda environments:                                                                                                   #                                                                                                                       base                  *  H:\one-click-installers-oobabooga-windows\installer_files\env                                  gptq                     H:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq                        gptq                     h:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq                                                                                                                                                                                                                                                                        (base) H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>conda activate gptq                                                                                                                          (gptq) H:\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install                                                                                                                 running install                                                                                                         H:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.      warnings.warn(                                                                                                        H:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.                                                                                                                   warnings.warn(                                                                                                        running bdist_egg                                                                                                       running egg_info                                                                                                        writing quant_cuda.egg-info\PKG-INFO                                                                                    writing dependency_links to quant_cuda.egg-info\dependency_links.txt                                                    writing top-level names to quant_cuda.egg-info\top_level.txt                                                            H:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.                                                                                             warnings.warn(msg.format('we could not find ninja.'))                                                                 reading manifest file 'quant_cuda.egg-info\SOURCES.txt'                                                                 writing manifest file 'quant_cuda.egg-info\SOURCES.txt'                                                                 installing library code to build\bdist.win-amd64\egg                                                                    running install_lib                                                                                                     running build_ext                                                                                                       H:\one-click-installers-oobabooga-windows\installer_files\env\envs\gptq\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Не удается найти указанный файл                     warnings.warn(f'Error checking compiler version for {compiler}: {error}')                                             building 'quant_cuda' extension                                                                                         error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ `
