### ISSUE TITLE
Separate CMD_FLAGS from webui.py

### ISSUE THREAD

**Issue by RaymondTracer** [oobabooga/one-click-installers#100]
It's annoying having to set CMD_FLAGS in webui.py each time you commit a new change to it, unless you're not going to change webui.py anymore, it might be a good idea to put the arguments in a separate file and have it read from that instead.

**Comment by jllllll** [comment]
The script supports loading flags from the `OOBABOOGA_FLAGS` environment variable. This allows you to create separate start scripts for different flag configurations and should allow you to not rely on `webui.py` for command-line flags.

Add one of these lines to your start script and modify it how you like:
- Windows: `set "OOBABOOGA_FLAGS=--chat --model None --api"`
- Linux/MacOS: `export OOBABOOGA_FLAGS="--chat --model None --api"`

**Comment by oobabooga** [comment]
I have added the CMD_FLAGS.txt file here https://github.com/oobabooga/one-click-installers/pull/117. If `OOBABOOGA_FLAGS` is set, it will still be used instead of the contents of this file.
