### ISSUE TITLE
Windows One-Click Installer set the option `trust_remote_code=True` to remove this error.

### ISSUE THREAD

**Issue by ghost** [oobabooga/one-click-installers#109]
Loading models\tiiuae_falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**Comment by jllllll** [comment]
The webui has a flag for setting this: `--trust-remote-code`

Add it to `CMD_FLAGS`:
```python
CMD_FLAGS = '--chat --trust-remote-code'
```
