### ISSUE TITLE
Error Critical libmamba

### ISSUE THREAD

**Issue by euri412** [oobabooga/one-click-installers#11]
I've been looking for this error that stops the installation and I don't understand what I'm doing wrong.

![Screenshot_2](https://user-images.githubusercontent.com/120108555/230629538-1c897ecf-69db-4c25-a6f6-df99a78cf74e.jpg)

I had read that it is a problem of the SSL that windows defend, that the servers... etc.

I am new at this. Sorry.

**Comment by jllllll** [comment]
Try this installer: https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda

I've heard Miniconda handles ssl better.
