### ISSUE TITLE
IndentationError: macos one click installer.

### ISSUE THREAD

**Issue by amalshehu** [oobabooga/one-click-installers#124]
1) Downloaded oobabooga_macos.zip
2) Ran ./start_macos.sh

IndentationError that occurred on line 203 of the webui.py file.
The corrective action involved ensuring that the code lines were correctly aligned with the intended logical block structure.
I can make a PR if needed.
<img width="1721" alt="Screenshot 2023-08-10 at 10 57 17 PM" src="https://github.com/oobabooga/one-click-installers/assets/12576673/37870082-83f7-4b6b-a506-a4e6b01d8352">

**Comment by oobabooga** [comment]
I have just fixed this, can you try updating webui.py?

**Comment by amalshehu** [comment]
Working. Thanks💚

**Comment by grande-dev** [comment]
Hi @oobabooga, thank you for promptly supporting this issue.
The same IndentationError arises when downloading the one-click-installer for Linux. 

As @amalshehu suggested, removing one tab on line 203 of webui.py fixes it.

Still waiting for the fix to propagate to the zipped installer into the parent repo, available for instance at "https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_linux.zip". I guess this will happen automatically? 

Many thanks.
