### ISSUE TITLE
Linux branch - install.sh: 18: Bad substitution

### ISSUE THREAD

**Issue by KaizerFox** [oobabooga/one-click-installers#16]
What is your GPU?

A) NVIDIA
B) AMD
C) None (I want to run in CPU mode)

Input> a
install.sh: 18: Bad substitution

**Comment by darthdeus** [comment]
> The Linux version is not being maintained right now. I have a universal one-click installer that I'll be creating a PR for that supports Windows, Linux, WSL, and even MacOS. I'm adding some final features but it should be up in a day or two and then you can use the Linux script.

I'm very curious in this, been trying to get the linux version working for a few hours today but unsuccessfully. Anything you have even if it's WIP but works is very much appreciated :)

**Comment by caterpillarpants** [comment]
if you install with './install.sh' or 'sh install.sh' you will get this error.

use the following to start install:
`bash install.sh`
