### ISSUE TITLE
cuda-nvvp-11.7.50-0.tar.bz2' critical libmamba Package cache error

### ISSUE THREAD

**Issue by agplusman** [oobabooga/one-click-installers#23]
I get the error for NVIDIA install A)

error libmamba Cannot find a valid extracted directory cache for 'cuda-nvvp-11.7.50-0.tar.bz2' critical libmamba Package cache error.

and its also mentioned here https://www.reddit.com/r/Oobabooga/comments/125e6it/the_windows_oneclick_installer_has_been_updated/

**Comment by jllllll** [comment]
Use this: https://github.com/jllllll/one-click-installers

Micromamba is just too unreliable. It works well for most, but there are enough people that can't get it to work. New installer is Miniconda based.
