### ISSUE TITLE
Linux install script failing to run on AWS Linux

### ISSUE THREAD

**Issue by mvresh** [oobabooga/one-click-installers#25]
I'm trying to run webui on AWS linux instance - t2.2xlarge with the following:

vCPU: 8
Memory: 32 GiB

Additionally, I provisioned 100GB storage. I'm running into this issue:

`0tar: Child died with signal 13
tar: Error is not recoverable: exiting now
  0 5051k    0 23942    0     0  16051      0  0:05:22  0:00:01  0:05:21  210k
curl: (23) Failure writing output to destination
Micromamba version:
Packages to install: pytorch torchvision torchaudio cpuonly conda git
There was a problem while initializing micromamba. Cannot continue.`

are there any dependencies I need to install first?

**Comment by xNul** [comment]
try now with the new one-click installers https://github.com/oobabooga/text-generation-webui#one-click-installers
