### ISSUE TITLE
AssertionError("Torch not compiled with CUDA enabled")

### ISSUE THREAD

**Issue by SilveonSenpai** [oobabooga/one-click-installers#27]
![зображення_2023-04-17_152312730](https://user-images.githubusercontent.com/90692714/232482794-924d023d-3e58-4efd-a1bf-cefba665e574.png)
So i was trying to run alpaca on with oobabooga webui, and got some errors: 
1.UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Torch not compiled with CUDA enabled.
After this one, it crashes. I used the universal one-click installation bcuz the mamba one didn't work.

**Comment by navyfighter12** [comment]
Same issue here. Haven't found a fix yet

**Comment by xNul** [comment]
@SilveonSenpai @navyfighter12 did you two install for CPU or GPU? (aka did you pick option A, B, C, or D when installing?)

**Comment by markgauda** [comment]
I am also getting that error. I installed with option A for NVIDIA GPU.

**Comment by jllllll** [comment]
This really shouldn't happen as the installer is set to specifically install the cuda Pytorch when gpu install is selected. Even if it wanted to install the cpu version, it would just fail to create the environment. Currently, the webui is using the `BITSANDBYTES_NOWELCOME` env var to hide the bitsandbytes welcome message. But, this also hides all of it's debug output that is kinda necessary to understand what is happening here.

**Comment by xNul** [comment]
@markgauda if you run `update_windows.bat`, do you receive an error at the end? Could you send the log?

**Comment by grosorg** [comment]
Same issue here. Yet with details.

OS: Ubuntu 20.04.6 LTS x86_64 
Host: XPS 13 9310 
Kernel: 5.15.49-051549-generic 
Shell: bash 5.0.17 

`$ ./start_linux.sh`

What is your GPU
A) NVIDIA
B) AMD
C) Apple M Series
**D) None (I want to run in CPU mode)**
Input> D

Select the model that you want to download:
A) OPT 6.7B
B) OPT 2.7B
C) OPT 1.3B
D) OPT 350M
E) GALACTICA 6.7B
F) GALACTICA 1.3B
G) GALACTICA 125M
**H) Pythia-6.9B-deduped**
I) Pythia-2.8B-deduped
J) Pythia-1.4B-deduped
K) Pythia-410M-deduped
L) Manually specify a Hugging Face model
M) Do not download a model
Input> H


Gradio HTTP request redirected to localhost :)
bin /home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading EleutherAI_pythia-6.9b-deduped...
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:07<00:00,  3.93s/it]
Traceback (most recent call last):
  File "/home/grosorg/Downloads/oobabooga_linux/text-generation-webui/server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/grosorg/Downloads/oobabooga_linux/text-generation-webui/modules/models.py", line 89, in load_model
    model = model.cuda()
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/grosorg/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Done!
[Log.odt](https://github.com/oobabooga/one-click-installers/files/11360865/Log.odt)

**Comment by grosorg** [comment]
`conda update --all`
That did not helped. 
[Log2.odt](https://github.com/oobabooga/one-click-installers/files/11360896/Log2.odt)

**Comment by xNul** [comment]
@grosorg the problem here is that you're trying to run a GPU model on the CPU. Only `ggml` and `hf` models are supported on the CPU like https://huggingface.co/Drararara/llama-7b-ggml

**Comment by grosorg** [comment]
@xNul Thank you.
Does it make sense to filter the choice if only CPU is selected?

Now I'm not sure which are the available options for such a choice.

Select the model that you want to download:
A) OPT 6.7B
B) OPT 2.7B
C) OPT 1.3B
D) OPT 350M
E) GALACTICA 6.7B
F) GALACTICA 1.3B
G) GALACTICA 125M
H) Pythia-6.9B-deduped
I) Pythia-2.8B-deduped
J) Pythia-1.4B-deduped
K) Pythia-410M-deduped
L) Manually specify a Hugging Face model
M) Do not download a model

**Comment by xNul** [comment]
@grosorg you're right and I've been meaning to raise this with @oobabooga. We should at the very least have an error which says that this model can't be run in CPU mode.

To download another model like the one I gave, you have to select the option L for manually specifying the model and then enter "Drararara/llama-7b-ggml"
