### ISSUE TITLE
Windows start unable to locate conda

### ISSUE THREAD

**Issue by olamedia** [oobabooga/one-click-installers#28]
Original start_windows.bat and others bat files fails to locate conda (not installed globally)
So, I moved PATH definition after setting %CONDA_ROOT_PREFIX% and appended  %CONDA_ROOT_PREFIX%\condabin;%CONDA_ROOT_PREFIX%\Scripts

```cmd
set CONDA_ROOT_PREFIX=%cd%\installer_files\conda
```

```cmd
set PATH=%PATH%;%SystemRoot%\system32;%CONDA_ROOT_PREFIX%\condabin;%CONDA_ROOT_PREFIX%\Scripts
```

**Comment by jllllll** [comment]
It's not supposed to need a global install. When the environment is activated, the relevant Conda paths are supposed to be added to PATH automatically. Odd that this didn't happen on your system.

**Comment by olamedia** [comment]
As I see, activate.bat sets %CONDA_EXE% but not the PATH

**Comment by olamedia** [comment]
activate.bat adds installer_files\env\Scripts to the PATH
while %CONDA_EXE% is at installer_files\conda\Scripts\conda.exe

**Comment by olamedia** [comment]
It looks like it should be set via
```
@DOSKEY conda="%CONDA_ROOT_PREFIX%\condabin\conda.bat" $*
```
But somehow DOSKEY command was failing or something. Trying to reinstall again.

**Comment by olamedia** [comment]
Found the problem, another app (Stable Diffusion) added Autorun to the Registry
```
"Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor" AutoRun
```

```
"B:\python\condabin\mamba_hook.bat" & if exist "D:\AI\stable-diffusion\miniconda3\condabin\conda_hook.bat" "D:\AI\stable-diffusion\miniconda3\condabin\conda_hook.bat"
```

**Comment by xNul** [comment]
@olamedia what installer did you use for Stable Diffusion?

**Comment by olamedia** [comment]
> @olamedia what installer did you use for Stable Diffusion?

I think, the different installers have messed up the environment.

"B:\python\condabin\mamba_hook.bat" looks like was created by KoboldAI's micromamba [umamba.exe](https://github.com/KoboldAI/KoboldAI-Client/blob/main/umamba.exe) 

Then miniconda3 was probably installed from regular installer, but found and used python from micromamba.
