### ISSUE TITLE
CUDA kernel compilation failed when running start_linux.sh

### ISSUE THREAD

**Issue by DIGist** [oobabooga/one-click-installers#29]
Running start_linux.sh, right before the model download options.

RuntimeError: 
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.

CUDA kernel compilation failed.

Unclear on how to resolve.

**Comment by jllllll** [comment]
Try prepending `python webui.py` on line 56 with `CUDA_PATH="$INSTALL_ENV_DIR"`.

Not a frequent Linux user, so not to sure on the syntax. I assume `CUDA_PATH="$INSTALL_ENV_DIR" python webui.py` Is the correct way to set the `CUDA_PATH` environment variable.

**Comment by xNul** [comment]
Yeah it looks like there could be another version of CUDA on your system and the installer is using it for some reason. CUDA 11 should have been installed, not 12.1. If @jllllll's answer doesn't work, maybe this will work: `"$INSTALL_ENV_DIR/bin/python" webui.py`.

**Comment by jllllll** [comment]
@xNul On Windows, I use the `CUDA_PATH` env variable to set which cuda toolkit I want to use when compiling. I have 7 versions of it installed. Some Python packages, such as bitsandbytes, search multiple other variables. On Linux, I believe it may be necessary to also set `LD_LIBRARY_PATH="${INSTALL_ENV_DIR}/lib64:${LD_LIBRARY_PATH}"`.

**Comment by xNul** [comment]
I tried to reproduce by installing CUDA-enabled pytorch system-wide and then installing with the one-click installer but failed. It might have something unique to WSL, but I don't have a Linux computer connected to an Nvidia GPU to test on.

@jllllll gotcha and yeah you might be right

**Comment by xNul** [comment]
@DIGist Could you open up `cmd_linux.sh`, use the command `set`, and send the log? It will help me look through your environment for any misconfigured variables which may be causing this.
