### ISSUE TITLE
MacOS unable to install using start_macos.sh

### ISSUE THREAD

**Issue by Kiru6ik** [oobabooga/one-click-installers#32]
Hi, I can't install it using the start_macos.sh. Once I run it I get the error: `Cloning into 'text-generation-webui'...                                         
dyld[65256]: Library not loaded: @rpath/libssl.1.1.dylib                        
  Referenced from: /Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/lib/libcurl.4.dylib                                                        
  Reason: tried: '/Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/lib/lib/libssl.1.1.dylib' (no such file), '/Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/libexec/git-core/../../lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/lib/lib/libssl.1.1.dylib' (no such file), '/Users/kirillevseev/Downloads/oobabooga_macos/installer_files/env/libexec/git-core/../../lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)                                                                          
error: git-remote-https died of signal 6                                        
Traceback (most recent call last):                                              
  File "/Users/kirillevseev/Downloads/oobabooga_macos/webui.py", line 162, in <module>                
    install_dependencies()
  File "/Users/kirillevseev/Downloads/oobabooga_macos/webui.py", line 60, in install_dependencies
    update_dependencies()
  File "/Users/kirillevseev/Downloads/oobabooga_macos/webui.py", line 64, in update_dependencies
    os.chdir("text-generation-webui")
FileNotFoundError: [Errno 2] No such file or directory: 'text-generation-webui'

Done!
`
So I installed git text-generation-webui manually. But then when I try running it again it fails on the server.py: no gradio module #30. However the I freshly installed anaconda, freshly installed gradio using pip, I also specified the path to gradio in the server.py file but I keep getting this error
Machine: MacOS 13.3.1 
Apple M1

**Comment by jllllll** [comment]
No gradio module means that the requirements,txt was not installed through pip. Run this in the conda environment:
```
cd text-generation-webui
python -m pip install -r requirements.txt
```

As for the error, my guess is that Conda did not install the correct version of git for your system for some reason. Possibly a bug in it's arch detection for MacOS?

A temporary fix for your system would be to add `-c conda-forge/osx-arm64` to the conda commands on lines 43 and 48 of `webui.py`. A more permanent fix could be to just add `-c conda-forge` and see if the arch detection is better with that channel.
