### ISSUE TITLE
compiling quant_cuda_kernel.o failed

### ISSUE THREAD

**Issue by jcl2023** [oobabooga/one-click-installers#33]
This is the error I got:

/home/test/2TB/GITS/text-generation-webui/one-click-installers/text-generation-webui/repositories/GPTQ-for-LLaMa/quant_cuda_kernel.cu(654): error: identifier "__hfma2" is undefined

Any idea why?

**Comment by jllllll** [comment]
The cuda GPTQ-for-LLaMa used by the webui is from oobabooga's fork which does not support GPUs older than Pascal. The latest cuda kernels from GPTQ support late-Kepler+ (compute 3.5+) and should work on your system. Though, you won't be able to run models quantized with ooba's fork with that.

Eventually, we should move to something like [0cc4m's fork](https://github.com/0cc4m/GPTQ-for-LLaMa) for broader GPU and model support.
