### ISSUE TITLE
"Error checking compiler version for cl" / Warning about Microsoft C++ Build tools required when updating

### ISSUE THREAD

**Issue by douchesfeedboard** [oobabooga/one-click-installers#36]
Hello,

I'm using the one-click-installer on Windows and when I use "update_windows.bat" to check and update the installer, at the very end, I get this warning :

![error checking compiler](https://user-images.githubusercontent.com/82176340/234095105-6246f26c-3006-455d-92ce-c36011a4f96a.PNG)

I indeed doesn't have the Microsoft C++ Build Tools installed. Should I install it? Is it really required? I'm using 4 bit quantized gptq models with a nvidia GPU and so far, it's working. Why does this warning about C++ Build Tools is appearing? Is there a situation or a model type where it should be installed?

**Comment by jllllll** [comment]
Open `cmd_windows.bat` and run this:
```
python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall
```
The installer is supposed to do this automatically when the compile fails. There must be something wrong with that detection.

**Comment by douchesfeedboard** [comment]
Thank you. The installer seem to correctly do it during the first installation with the start_windows.bat because I did a fresh reinstall to test it (I also cleaned the pip cache folder) and while using the start_windows.bat , the wheel is correctly downloaded if the compilation fail and after the warning message : 

![start](https://user-images.githubusercontent.com/82176340/234368841-e52a5fd0-c726-4e70-aaea-1e4f6ff0fd9a.PNG)

It's only while using the update_windows.bat file you there is no download and only the warning :

![update](https://user-images.githubusercontent.com/82176340/234369039-ceeba918-bae9-4733-b607-89a59fb11af3.PNG)

So maybe, because the file was already downloaded previously (with start_windows.bat) , only the warning is displayed and there is no need to download it again.

**Comment by jllllll** [comment]
Sorry, I mistakenly read `update_windows.bat` as `start_windows.bat` because I was in a hurry.

The backup quant_cuda wheel is only downloaded and installed when quant_cuda is not already installed. The script needs to be updated to also only try compiling when quant_cuda is missing. It should be harmless regardless. Just wastes time trying to compile something that is already installed.

**Comment by xNul** [comment]
Yeah there's no point in reinstalling the wheel because it's a fixed version. It's strange that you're getting the Microsoft Build Tools not found error because the compiler should be installed with the `cuda-toolkit` package. This could be an issue related to the environment. If so, I've made changes to the one-click installers which may fix it https://github.com/xNul/one-click-installers

**Comment by jllllll** [comment]
> Yeah there's no point in reinstalling the wheel because it's a fixed version. It's strange that you're getting the Microsoft Build Tools not found error because the compiler should be installed with the `cuda-toolkit` package. This could be an issue related to the environment. If so, I've made changes to the one-click installers which may fix it https://github.com/xNul/one-click-installers

`cuda-toolkit` only provides the cuda compiler. On Windows, a separate installation of Visual Studio is needed for a C compiler and also possibly a separate installation of Cuda Toolkit for it's Visual Studio integration. Basically, it is way harder for Windows users to compile Cuda extensions than it is for Linux. I've even encountered issues with specific Cuda versions working with only one older MSVC version.

**Comment by xNul** [comment]
@jllllll gotcha, that's strange because I thought I uninstalled all my versions of Visual Studio but I'm still able to compile. Guess I still have an install lurking somewhere in my PATH

**Comment by Loufe** [comment]
I'm having a similar issue. I feel like I've removed visual studio build tools from path but it's still being recognized somehow.

During install of the webui I get a failed build of GPTQ (for that reason). Thankfully it tries to install your wheel, @jllllll . However despite saying it's been installed successfully I'm getting this error when I try to run.

![image](https://user-images.githubusercontent.com/5817861/234939198-53dcceec-95a4-49d9-82b9-6da4a971ec0e.png)

Is there not a bundled compiler in the environment that should be used for building GPTQ? I feel like my path contents should be irrelevant here.

**Comment by Loufe** [comment]
@xNul installed for NVidia and ran a GPTQ model, I think it was a classic llama but 4bit GPTQ 128g

**Comment by xNul** [comment]
@Loufe ok that should be working. Do you have a folder starting with `quant_cuda` under the `installer_files\env\Lib\site-packages` directory?
