### ISSUE TITLE
Power off after 3 or 4 input to the webui

### ISSUE THREAD

**Issue by cemo702** [oobabooga/one-click-installers#40]
i Have 3090 which i bought used a month ago when i start to chat after 3. or 4. text that i sent power goes off on my pc.
i have same issue wih Stable diffussion but not that often. it happend more when i make hires.
can you help me to solve that problem pls

**Comment by JulianKauth** [comment]
Is your power supply powerful enough to power the 3090 at full speed? If it's not just a black screen issue, but the whole PC turns off, including all fans, that sounds like your power supply protection kicks in.

**Comment by cemo702** [comment]
Yeah it was POWER issue from my power sup. when i changed it it gone
Thank you
