### ISSUE TITLE
Help... how to fix this part "unexpected keyword argument 'font'"

### ISSUE THREAD

**Issue by StableDiffusionPlsWork** [oobabooga/one-click-installers#41]
D:\School\Quarter3\oobabooga_windows>conda activate textgen
'conda' is not recognized as an internal or external command,
operable program or batch file.

D:\School\Quarter3\oobabooga_windows>cd text-generation-webui

D:\School\Quarter3\oobabooga_windows\text-generation-webui>python server.py
Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "D:\School\Quarter3\oobabooga_windows\text-generation-webui\server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "D:\School\Quarter3\oobabooga_windows\text-generation-webui\modules\training.py", line 16, in <module>
    from modules import shared, ui
  File "D:\School\Quarter3\oobabooga_windows\text-generation-webui\modules\ui.py", line 18, in <module>
    theme = gr.themes.Default(
TypeError: Default.__init__() got an unexpected keyword argument 'font'

**Comment by xNul** [comment]
I'm not sure what you're doing. Just use the one-click installers https://github.com/oobabooga/text-generation-webui#one-click-installers

**Comment by StableDiffusionPlsWork** [comment]
> 

I did, I repeat the whole process twice now and this still shows up. I already have my models and anything.

This only shows up when I try to get the localhost server by cmd-ing: 

conda activate textgen
cd text-generation-webui
python server.py

to my main oogabooga folder.

Thx for the reply

**Comment by xNul** [comment]
there's no need to use the command prompt with the one-click installer. When you double click on `start_windows.bat`, webui will be installed and started automatically. If you shut it down then you just use `start_windows.bat` to run it again. Make sure you have a model downloaded or it will never start up

**Comment by StableDiffusionPlsWork** [comment]
Oh so that's why. I see, thx for the advice!!

**Comment by xNul** [comment]
np!
