### ISSUE TITLE
Traceback at the end of the update since the commit 4babb22f846e74f096af5f487a2b4a6942b3f3c3

### ISSUE THREAD

**Issue by douchesfeedboard** [oobabooga/one-click-installers#48]
Hello,

I did a fresh install with the lastest files from the commit 4babb22f846e74f096af5f487a2b4a6942b3f3c3 and I'm noticing a traceback when using update_windows.bat

`Traceback (most recent call last):
  File "G:\oobabooga_windows\webui.py", line 175, in <module>
    update_dependencies()
  File "G:\oobabooga_windows\webui.py", line 133, in update_dependencies
    os.rename("setup_cuda.py", "setup.py")
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'setup_cuda.py' -> 'setup.py'`

Seem the file setup_cuda.py is missing. I don't know if it could be related to the failed CUDA kernel compilation during the installation (because of missing microsoft c++ compiler) but the wheel got correctly downloaded instead.

**Comment by Googolplexed06** [comment]
I have all of the same issues when doing a fresh install. First quant_cuda fails to build due to lacking C++ >= 14.0. Everything installed and ran correctly prior to https://github.com/oobabooga/one-click-installers/commit/4babb22f846e74f096af5f487a2b4a6942b3f3c3. I also noticed that several dependencies would not be installed due to them being found in my main install of python (on a completely different drive) rather than checking for them in the conda venv. Could this misattribution of packages be the cause?

```
Processing e:\ai\oobabooga-windows_v2\text-generation-webui\repositories\gptq-for-llama
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error

  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ERROR: GPTQ CUDA kernel compilation failed.
Attempting installation with wheel.
Collecting quant-cuda==0.0.0
  Using cached https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
Installing collected packages: quant-cuda
Successfully installed quant-cuda-0.0.0
Wheel installation success!
```

At this point the installation asks me to download a model and then terminates. 

Also, when running the text-generation-webui, upon closing the executable I get the error:

`C:\arrow\cpp\arrow\filesystem\s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit`

This error does not appear when closing the executable when the ui is built using the installer prior to https://github.com/oobabooga/one-click-installers/commit/4babb22f846e74f096af5f487a2b4a6942b3f3c3. This error seems especially odd given that I am running everything on my E:\ drive and no C:\arrow directory exists, while arrow can be found within `site-packages\pyarrow\include`. I know this second error belongs on the main text-generation-webui error section but thought I'd mention it here since it may be related

**Comment by xNul** [comment]
> Hello,
> 
> I did a fresh install with the lastest files from the commit [4babb22](https://github.com/oobabooga/one-click-installers/commit/4babb22f846e74f096af5f487a2b4a6942b3f3c3) and I'm noticing a traceback when using update_windows.bat
> 
> `Traceback (most recent call last): File "G:\oobabooga_windows\webui.py", line 175, in <module> update_dependencies() File "G:\oobabooga_windows\webui.py", line 133, in update_dependencies os.rename("setup_cuda.py", "setup.py") FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'setup_cuda.py' -> 'setup.py'`
> 
> Seem the file setup_cuda.py is missing. I don't know if it could be related to the failed CUDA kernel compilation during the installation (because of missing microsoft c++ compiler) but the wheel got correctly downloaded instead.

This should be fixed since https://github.com/oobabooga/one-click-installers/commit/126d216384b65e28936a432a7a5514907f0c5b92

**Comment by xNul** [comment]
> I have all of the same issues when doing a fresh install. First quant_cuda fails to build due to lacking C++ >= 14.0. Everything installed and ran correctly prior to [4babb22](https://github.com/oobabooga/one-click-installers/commit/4babb22f846e74f096af5f487a2b4a6942b3f3c3). I also noticed that several dependencies would not be installed due to them being found in my main install of python (on a completely different drive) rather than checking for them in the conda venv. Could this misattribution of packages be the cause?
> 
> ```
> Processing e:\ai\oobabooga-windows_v2\text-generation-webui\repositories\gptq-for-llama
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: quant-cuda
>   Building wheel for quant-cuda (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       running bdist_wheel
>       running build
>       running build_ext
>       E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>         warnings.warn(f'Error checking compiler version for {compiler}: {error}')
>       building 'quant_cuda' extension
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for quant-cuda
>   Running setup.py clean for quant-cuda
> Failed to build quant-cuda
> Installing collected packages: quant-cuda
>   Running setup.py install for quant-cuda ... error
>   error: subprocess-exited-with-error
> 
>   × Running setup.py install for quant-cuda did not run successfully.
>   │ exit code: 1
>   ╰─> [9 lines of output]
>       running install
>       E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       running build
>       running build_ext
>       E:\AI\oobabooga-windows_v2\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>         warnings.warn(f'Error checking compiler version for {compiler}: {error}')
>       building 'quant_cuda' extension
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> quant-cuda
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
> ERROR: GPTQ CUDA kernel compilation failed.
> Attempting installation with wheel.
> Collecting quant-cuda==0.0.0
>   Using cached https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
> Installing collected packages: quant-cuda
> Successfully installed quant-cuda-0.0.0
> Wheel installation success!
> ```
> 
> At this point the installation asks me to download a model and then terminates.
> 
> Also, when running the text-generation-webui, upon closing the executable I get the error:
> 
> `C:\arrow\cpp\arrow\filesystem\s3fs.cc:2598: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit`
> 
> This error does not appear when closing the executable when the ui is built using the installer prior to [4babb22](https://github.com/oobabooga/one-click-installers/commit/4babb22f846e74f096af5f487a2b4a6942b3f3c3). This error seems especially odd given that I am running everything on my E:\ drive and no C:\arrow directory exists, while arrow can be found within `site-packages\pyarrow\include`. I know this second error belongs on the main text-generation-webui error section but thought I'd mention it here since it may be related

For your first issue, I know this error can be misleading but this library was actually installed correctly. It failed to compile, but it the installation from the wheel was successful.

The model download termination is a problem though. Is it possible you gave an invalid model name to download? If you can tell me exactly what you inputted at that part of the installation, I may be able to help.
