### ISSUE TITLE
start_windows.bat does not appear "Running on local URL : https//127.0.0.1:7860..."

### ISSUE THREAD

**Issue by Dany19212050** [oobabooga/one-click-installers#50]
I downloaded and used one-click-installers and installed without errors,but it does not appear "Running on local URL : https//127.0.0.1:7860..."How to solve this problem？
<img width="1271" alt="屏幕截图 2023-05-04 115824" src="https://user-images.githubusercontent.com/132433940/236109111-109d22e3-41c3-40dd-920c-6c42a2df5bff.png">

**Comment by xNul** [comment]
Does this model work for you or does the same problem happen? https://huggingface.co/wcde/llama-7b-4bit-gr128
