### ISSUE TITLE
Can't install on Kubuntu

### ISSUE THREAD

**Issue by ghost** [oobabooga/one-click-installers#51]
./start_linux.sh: 3: Bad substitution
./start_linux.sh: 5: [[: not found
./start_linux.sh: 27: [: T: unexpected operator
./start_linux.sh: 23: /home/Yukkun/.local/share/Trash/files/oobabooga_linux/installer_files/conda/bin/conda: not found
./start_linux.sh: 43: /home/Yukkun/.local/share/Trash/files/oobabooga_linux/installer_files/conda/bin/conda: not found
Conda environment is empty.

I keep just getting this error. Running it with or without sudo doesn't seem to change anything

**Comment by xNul** [comment]
Hmm this looks like a problem with parsing the Bash script. Try running the script with `bash start_linux.sh`, does the error still happen? There should be no need to run with sudo btw. Make sure you delete all the files beforehand for a clean install.

Also, what OS and shell are you using?
