### ISSUE TITLE
I am unable to install the webui ERROR: Could not install packages due to an OSError:

### ISSUE THREAD

**Issue by AlexanderMach3** [oobabooga/one-click-installers#52]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA92980>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA92C20>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA92DA0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA92E90>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA93010>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jllllll/bitsandbytes-windows-webui/main/bitsandbytes-0.38.1-py3-none-any.whl (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024E0EA93190>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)'))

Command '"D:\AI\oobabooga_windows\installer_files\conda\condabin\conda.bat" activate "D:\AI\oobabooga_windows\installer_files\env" >nul && python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl' failed with exit status code '1'. Exiting...

Done!
Press any key to continue . . .

please let me know what other information I need to provide

CPU : AMD Ryzen 5 5600X
GPU : Nvidia RTX 3060
RAM : 16 GB DDR4 3600 Mhz

**Comment by xNul** [comment]
Looks like you are/were having problems connecting to GitHub. GitHub had some outage issue awhile ago, maybe that's the problem? No one else has this issue so try reinstalling again and if you still have the connection problem, there's probably something specific to your system causing it. Some network tool intercepting your packets or internal corporate firewall.
