### ISSUE TITLE
update_windows error

### ISSUE THREAD

**Issue by cmariotti** [oobabooga/one-click-installers#56]
After an initial installation that appears successful (no errors from what I could see), I ran the update_windows.bat file to make sure it is updated as needed and received the following error at the end of execution:

Requirement already satisfied: sniffio>=1.1 in c:\users\digdug01\desktop\one-click-installers-main\installer_files\env\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.27.0,>=0.26.1->fastapi>=0.85.1->chromadb==0.3.18->-r extensions\superbig\requirements.txt (line 2)) (1.3.0)
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
Command '"C:\Users\DigDug01\Desktop\one-click-installers-main\installer_files\conda\condabin\conda.bat" activate "C:\Users\DigDug01\Desktop\one-click-installers-main\installer_files\env" >nul && python -m pip install -r extensions\superbig\requirements.txt --upgrade' failed with exit status code '1'. Exiting...

Done!
Press any key to continue . . .

**Comment by cmariotti** [comment]
I should clarify, this happened with the update option, but then I downloaded the Windows Installer (May 7) and tried a fresh installation which resulted in the same error.

**Comment by DocShotgun** [comment]
Same error here on a fresh install. Looks like it's trying to build a wheel locally and we don't have build tools installed.

**Comment by tk101-fs** [comment]
Same issue here. One-click installer now seems to run into this issue on some (all?) fresh installs?

**Comment by ktostest** [comment]
it worked for me
https://visualstudio.microsoft.com/visual-cpp-build-tools/
![instalacja probrmy doinstalowac visual studio ](https://user-images.githubusercontent.com/124760918/236725349-aadef8fa-beca-40f0-86c7-b20934cab145.png)

**Comment by NeuralBlankes** [comment]
Still getting this same error, in spit of having the VS build tools.

**Comment by jllllll** [comment]
I have asked the `hnswlib` devs to setup automatic wheel building. If they do, this will no longer be an issue. This issue is arising due to one of the dependencies of the extension `superbooga`, formerly `superbig`, requiring `hnswlib` which does not have prebuilt wheels available to install.

A short-term workaround for this would be to exclude installing the `superbooga` extension with the installer.

**Comment by oobabooga** [comment]
I have removed superbooga from the installer for now https://github.com/oobabooga/one-click-installers/commit/b8cfc20e58d72489f09fc937cd837be842ad43d6

This extension is very experimental and might change. It's best to only include it once it settles down

**Comment by NeuralBlankes** [comment]
I went through the install process one more time, and, while I don't know what possessed me to do it, I tried just going ahead and trying to run it in spite of the error.  I have no understanding of why, but it's working.   I don't know that it's working *correctly* but it appears that there is some functionality to it even though the error was still showing up.
I appreciate the assistance on this.  Looking forward to updates on this webUI.

**Comment by jllllll** [comment]
> I went through the install process one more time, and, while I don't know what possessed me to do it, I tried just going ahead and trying to run it in spite of the error. I have no understanding of why, but it's working. I don't know that it's working _correctly_ but it appears that there is some functionality to it even though the error was still showing up. I appreciate the assistance on this. Looking forward to updates on this webUI.

Error shouldn't happen anymore after the most recent update. Worst case scenario, I think you will just be missing GPTQ and be unable to run 4bit models.

**Comment by Kippykip** [comment]
2023-07-03 01:41:15 ERROR:Failed to load the extension "superbooga".
Traceback (most recent call last):
  File "C:\MachineLearning\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\MachineLearning\oobabooga_windows\text-generation-webui\extensions\superbooga\script.py", line 10, in <module>
    from .chromadb import add_chunks_to_collector, make_collector
  File "C:\MachineLearning\oobabooga_windows\text-generation-webui\extensions\superbooga\chromadb.py", line 1, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'
Running on local URL:  http://0.0.0.0:7860

**Comment by jllllll** [comment]
> 2023-07-03 01:41:15 ERROR:Failed to load the extension "superbooga". Traceback (most recent call last): File "C:\MachineLearning\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions exec(f"import extensions.{name}.script") File "", line 1, in File "C:\MachineLearning\oobabooga_windows\text-generation-webui\extensions\superbooga\script.py", line 10, in from .chromadb import add_chunks_to_collector, make_collector File "C:\MachineLearning\oobabooga_windows\text-generation-webui\extensions\superbooga\chromadb.py", line 1, in import chromadb ModuleNotFoundError: No module named 'chromadb' Running on local URL: http://0.0.0.0:7860

Requirements for superbooga are not automatically installed due to the need for a compiler to install one or more of them.
Run `cmd_windows.bat` and enter this command to install them:
```
python -m pip install -r .\text-generation-webui\extensions\superbooga\requirements.txt
```

**Comment by Kippykip** [comment]
> python -m pip install -r .\text-generation-webui\extensions\superbooga\requirements.txt
Yee, okay so I already ran that command from another thread, which installed a bunch of stuff then errored out where it made me install this first:
https://visualstudio.microsoft.com/visual-cpp-build-tools/
Then the command worked fine and all dependancies are met in that requirements txt file. 

But when I launch oogabooga I still get that chromadb error?
![image_2023-07-03_090814978](https://github.com/oobabooga/one-click-installers/assets/33023808/763844e9-ab8c-4f87-96bc-af91aa786831)

**Comment by Kippykip** [comment]
Figured it out using a cached reddit thread:
https://webcache.googleusercontent.com/search?q=cache:v1_-orVDrYMJ:https://www.reddit.com/r/Oobabooga/comments/13v0mbw/superbooga_failing_to_load_modulenotfounderrror/&cd=12&hl=en&ct=clnk&gl=au&client=opera-gx

You have to run cmd_windows.bat first to put it into some isolated conda enviroment or something, then run the commands. Then it works fine? :D
