### ISSUE TITLE
"Conda is not installed"

### ISSUE THREAD

**Issue by Jordunnn** [oobabooga/one-click-installers#58]
Everytime ive tried to run the one click installer, tells me "Conda is not installed" When it very much is.
Ive uninstalled and reinstalled conda, I've deleted the files and redownloaded and installed everything. Still the same "Conda is not installed" Even though I've even downloaded and ran the OB UI through co
<img width="762" alt="Screenshot_1" src="https://github.com/oobabooga/one-click-installers/assets/129976842/b40ad6aa-1015-4ec6-b37e-481d8dcf247a">
nda itself.

**Comment by LBanovic** [comment]
Ran into the same problem. As far as I can tell, it is not added to the SHELL/Path properly.

A workaround that worked for me was manually running `conda init <your-shell-name>` from .../installer_files/conda/bin. This adds `conda activate/deactivate` to your shell (possibly needs to restart). After that, running `conda activate` in text-generation-webui seemed to work properly.

**Comment by clort81** [comment]
```
one-click-installers$ bash start_linux.sh 
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-aarch64.sh to /dir/Neural/oobabooga/one-click-installers/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.6M  100 51.6M    0     0   618k      0  0:01:25  0:01:25 --:--:--  827k
PREFIX=/dir/Neural/oobabooga/one-click-installers/installer_files/conda
Unpacking payload ...
/dir/Neural/oobabooga/one-click-installers/installer_files/miniconda_installer.sh: line 358: 4139738 Illegal instruction     "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs
Miniconda version:
start_linux.sh: line 38: /dir/Neural/oobabooga/one-click-installers/installer_files/conda/bin/conda: No such file or directory
start_linux.sh: line 43: /dir/Neural/oobabooga/one-click-installers/installer_files/conda/bin/conda: No such file or directory
Conda environment is empty.
```

**Comment by xNul** [comment]
@Jordunnn that error happens when the Python script tries to use the conda binary and the binary is unable to be found/used in the current environment. In VSCode, try to use the conda command and see what output you get. Also, I've never run it with PowerShell before. Maybe running it via VSCode Command Prompt Terminal would help?
