### ISSUE TITLE
Connect oobabooga with sillytavern

### ISSUE THREAD

**Issue by zetman85** [oobabooga/one-click-installers#65]
Hi, i'm a total noob so hope please help me in the easy way. I'd installed oobabboga and sillytavern, now i must connect them together, and this is the hard part. What i should do, i open webui and add something. What i must add and where?

**Comment by georgebanjog** [comment]
open webui.py, add --api flag to CMD_FLAGS, start oobabooga, start sillytavern, click - connect. That's all.
