### ISSUE TITLE
Suggestion: Adding the ability to pass in CLI params from a Windows batch files to `webui.py`

### ISSUE THREAD

**Issue by mikehdt** [oobabooga/one-click-installers#70]
This is a suggestion, I'd be happy to raise a PR if you feel this would be something worth implementing.

At the moment, if you have some models that are fussy (eg. needing to offload layers, specify model type etc.), then the default `start_windows.bat` and `webui.py` don't make this too easy, as the CLI params for Ooba are in the `webui.py` file hard-coded as:
```python
CMD_FLAGS = '--chat --model-menu'
```

I'm no Python coder, but if we change the above line to something like:
```python
user_cmd_flags = os.getenv('CMD_FLAGS')

if user_cmd_flags == 'None':
    CMD_FLAGS = '--chat --model-menu'
else:
    CMD_FLAGS = user_cmd_flags
```

Then in the `start_windows.bat` you can make a copy of it, eg. `start_fussy_model.bat` and then add something like this:
`set CMD_FLAGS=--chat --auto-devices --model some-model-name --wbits 4 --groupsize 128 --sdp-attention --api`

Or whatever you want, without needing to go through the model selection menu. As the default menu selector may not work for all models, such as models that are larger than your GPU memory allows. Also you might not want to change the default settings (in `webui.py`) for _all_ models.

What do you think? Or is there a better way to achieve this?

**Comment by xNul** [comment]
There's a PR for it here https://github.com/oobabooga/one-click-installers/pull/59 I would also like to see this merged.
