### ISSUE TITLE
Problems installing under linux \ wsl

### ISSUE THREAD

**Issue by razvanab** [oobabooga/one-click-installers#95]
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
/bin/sh: 5: /home/user/dev/one-click-installers/installer_files/env/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected
/bin/sh: 5: /home/user/dev/one-click-installers/installer_files/env/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected

*******************************************************************
* WARNING: GPTQ-for-LLaMa compilation failed, but this is FINE and can be ignored!
* The installer will proceed to install a pre-compiled wheel.
*******************************************************************

/bin/sh: 5: /home/user/dev/one-click-installers/installer_files/env/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected
ERROR: GPTQ wheel installation failed. You will not be able to use GPTQ-based models.
Continuing with install..

*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************

/bin/sh: 5: /home/user/dev/one-click-installers/installer_files/env/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected

**Comment by xehn** [comment]
Did you ever figure this out?  I am getting the same errors on a completely fresh Debian 12 install.  I feel like it must be something basic.

**Comment by jllllll** [comment]
The gxx_linux-64 packages from the main channel may be broken. Does this fix it:
```
conda install gxx_linux-64=11.2.0 -c conda-forge
```

**Comment by xehn** [comment]
@jllllll It did, thank you for your help.
