### ISSUE TITLE
One Click installer fails on Windows on "no OPENSSL_Applink"

### ISSUE THREAD

**Issue by GabrielZigelboim** [oobabooga/one-click-installers#99]
changed the script to verbose. 
This is the output:

D:\Z_oobabooga_windows>cd /D "D:\Z_oobabooga_windows\"

D:\Z_oobabooga_windows>set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseHg\;C:\Program Files\MATLAB\R2022b\bin;C:\Users\localUser\AppData\Local\Microsoft\WindowsApps;;C:\Windows\system32

D:\Z_oobabooga_windows>echo "D:\Z_oobabooga_windows"  | findstr /C:" "   1>nul  && echo This script relies on Miniconda which can not be silently installed under a path with spaces.   && goto end

D:\Z_oobabooga_windows>set "SPCHARMESSAGE="WARNING: Special characters were detected in the installation path!" "         This can cause the installation to fail!""

D:\Z_oobabooga_windows>echo "D:\Z_oobabooga_windows"  | findstr /R /C:"[!#\$&()\*+,;<=>?@\[\]\^`{|}~]"   1>nul  && (call :PrintBigMessage "WARNING: Special characters were detected in the installation path!" "         This can cause the installation to fail!" )

D:\Z_oobabooga_windows>set SPCHARMESSAGE=

D:\Z_oobabooga_windows>set TMP=D:\Z_oobabooga_windows\installer_files

D:\Z_oobabooga_windows>set TEMP=D:\Z_oobabooga_windows\installer_files

D:\Z_oobabooga_windows>set INSTALL_DIR=D:\Z_oobabooga_windows\installer_files

D:\Z_oobabooga_windows>set CONDA_ROOT_PREFIX=D:\Z_oobabooga_windows\installer_files\conda

D:\Z_oobabooga_windows>set INSTALL_ENV_DIR=D:\Z_oobabooga_windows\installer_files\env

D:\Z_oobabooga_windows>set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe

D:\Z_oobabooga_windows>set conda_exists=F

D:\Z_oobabooga_windows>call "D:\Z_oobabooga_windows\installer_files\conda\_conda.exe" --version  1>nul 2>&1

D:\Z_oobabooga_windows>if "0" EQU "0" set conda_exists=T

D:\Z_oobabooga_windows>if "T" == "F" (
echo Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe to D:\Z_oobabooga_windows\installer_files\miniconda_installer.exe
 mkdir "D:\Z_oobabooga_windows\installer_files"
 call curl -Lk "https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe"   1>"D:\Z_oobabooga_windows\installer_files\miniconda_installer.exe"  || (echo.   && echo Miniconda failed to download.   && goto end  )
 echo Installing Miniconda to D:\Z_oobabooga_windows\installer_files\conda
 start /wait "" "D:\Z_oobabooga_windows\installer_files\miniconda_installer.exe" /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=D:\Z_oobabooga_windows\installer_files\conda

 echo Miniconda version:
 call "D:\Z_oobabooga_windows\installer_files\conda\_conda.exe" --version   || (echo.   && echo Miniconda not found.   && goto end  )
)

D:\Z_oobabooga_windows>if not exist "D:\Z_oobabooga_windows\installer_files\env" (
echo Packages to install:
 call "D:\Z_oobabooga_windows\installer_files\conda\_conda.exe" create --no-shortcuts -y -k --prefix "D:\Z_oobabooga_windows\installer_files\env" python=3.10   || (echo.   && echo Conda environment creation failed.   && goto end  )
)
Packages to install:
Collecting package metadata (current_repodata.json): - OPENSSL_Uplink(00007FFAB63CBD50,08): no OPENSSL_Applink

Conda environment creation failed.

D:\Z_oobabooga_windows>pause
Press any key to continue . . .

**Comment by numbfx** [comment]
I'm having the same issue
